### ISSUE TITLE
Importing gin-gonic/gin.v1

### ISSUE THREAD

**Issue by mdonnellyli** [betacraft/yaag#25]
I import the versioned gin framework and its causing I think its causing problems. Any ideas on how to fix?

cannot use "github.com/betacraft/yaag/gin".Document() (type "github.com/gin-gonic/gin".HandlerFunc) as type "placeable.com/audit-service/vendor/gopkg.in/gin-gonic/gin.v1".HandlerFunc in argument to r.Use

**Comment by distravantari** [comment]
Im experiencing the same issue

**Comment by aniketawati** [comment]
This is fixed now. Gin's new versioned deps were not updated here.

**Comment by distravantari** [comment]
yea it seems I forgot to add "github.com/betacraft/yaag/gin" to govendor
