### ISSUE TITLE
Middleware for iris-go

### ISSUE THREAD

**Issue by sankethpb** [betacraft/yaag#32]
Hello all,

It would be great if you could provide a middleware for iris-go framework.
https://github.com/kataras/iris

Thanks,
Sanketh

**Comment by sankethpb** [comment]
Thanks a lot to @hiveminded and @kataras for adding yaag support to [iris-go](https://github.com/kataras/iris) so quickly.

**Comment by sankethpb** [comment]
@aniketawati @akshaydeo @hummerd , could you please merge the iris-go support?
Thanks in advance.

**Comment by aniketawati** [comment]
That was fast :) Merged - cfdf5955358d9aad8d0228142f57e588dd20d0fd 👍

**Comment by kataras** [comment]
You're welcome @sankethpb, just saw this issue! @aniketawati  I did push a PR  to improve the @hiveminded 's (excellent) initial code in order to be able to show the response body as well :)

**Comment by hiveminded** [comment]
@sankethpb you are welcome,  don't hesitate to ask any further feature requests
