### ISSUE TITLE
Not working with Revel

### ISSUE THREAD

**Issue by Fyb3roptik** [betacraft/yaag#38]
This is not working with revel. Also where will it store apidoc.html?

**Comment by aniketawati** [comment]
Full revel example is now added in examples dir and readme has the sample code. 
ApiDoc is generated at the path specified in yaag config while calling yaag.Init

**Comment by Fyb3roptik** [comment]
Docpath is not starting from app path and instead starts at root /

**Comment by aniketawati** [comment]
If you give a relative path, it will start from the directory in which revel command was run which is usually root folder.
