### ISSUE TITLE
Implementing yaag into existing project

### ISSUE THREAD

**Issue by sh4t** [betacraft/yaag#4]
I currently have a moderately sized API that is in ongoing development and I came across your "yaag" project and thought I would give it a whirl.  I checked out our martini branch and started implementing as your README.md dictates.  

I made sure to import the two yaag libraries: yaag/yaag and yaag/martiniyaag

Added: m.Use(martiniyaag.Document) 

I now have so many damn m.Use statements it is getting out of control ;)

That seems to be all that is necessary other than initiating the config option in my main(), which I did as well.  Do you know if utilizing route groups with Martini would prevent this from working as expected?  Currently I leverage m.Group() for all of our routes.

**Comment by aniketawati** [comment]
I think the martiniyaag middleware should work with route groups. We haven't tested it, but I don't see any issues in it. 

Did you try it?
